config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  resources :users, only: [:index] do
    post :impersonate, on: :member
    post :stop_impersonating, on: :collection
  end

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: { user: 0, admin: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    impersonates :user
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin
  def index
    @users = User.all
  end

  def impersonate
    user = User.find(params[:id])
    impersonate_user(user)
    redirect_to root_path
  end

  def stop_impersonating
    stop_impersonating_user
    redirect_to root_path
  end

  private

  # Redirect if true user is not an admin
  def require_admin
    # Will not let you see admin tools when impersonating normal user
    # redirect_to root_path, notice: "Go away, you're no admin" unless current_user.admin?

    # Will let you see admin tools when impersonating normal user
    redirect_to root_path unless true_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Video</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<p style="color: red"> <%= notice %></p>
<% if current_user %>
  <h1>Hello, <%= current_user.email %>!</h1>
  <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete } %>
<% else %>
  <h1>Home</h1>
  <%= link_to "Sign in", new_user_session_path %>
<% end %>
<% if current_user != true_user %>
  <hr />
  You (<%= true_user.email %>) are signed in as <%= current_user.email %>
  <%= link_to "Back to admin", stop_impersonating_users_path, data: { turbo_method: :post } %>
<% end %>
<br />
<%= link_to "Admin Panel", users_path %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>
<ul>
  <% @users.each do |user| %>
    <li>Sign in as <%= link_to user.email, impersonate_user_path(user), data: { turbo_method: :post } %></li>
  <% end %>
</ul>